### ISSUE TITLE
Recurso repetido

### ISSUE THREAD

**Issue by SanMe05** [fernandomoraangel/simr#28]
El Patojo está dos veces en la tabla de fonogramas con facetas distintas pero en el mismo volumen sonoro, ¿se ingresan ambos recursos?

**Comment by fernandomoraangel** [comment]
Es un solo recurso, con 2 ejemplares. Hay que borrar uno y registrar los 2 ejemplares para el otro.

**Comment by fernandomoraangel** [comment]
Es un solo recurso, con 2 ejemplares. Hay que borrar uno y registrar los 2 ejemplares para el otro.
